### ISSUE TITLE
Promise.defer is not part of the Promise API anymore...

### ISSUE THREAD

**Issue by davidhariri** [yarivr/lp-labs-agent-sdk#11]
This package doesn't run on Node 8.4.0 because the Promise API has changed and the stale references to .defer are busted. I'll try and fix locally for a while here and open a PR if I'm confident in my solution. Any branch open on your end with fixes for this?

**Comment by asafh** [comment]
Hi David,
This repo isn't actively maintained anymore so there isn't any branch with fixes.  
One option is you could switch to the official SDK [here](https://github.com/LivePersonInc/node-agent-sdk) - although it uses callbacks rather than promises.  
Alternatively, if you create a PR, I could take a look at it and merge it. Keep in mind I won't be able to publish the new package (I can try contacting Yariv but we're both no longer employed by LP) - you'd have to npm install GIT_URL.

**Comment by davidhariri** [comment]
Thanks @asafh - It's all good. I ended using that other SDK. Thanks.
